#!/bin/bash
if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

echo 'Setting Permissions'
echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="0fc5", MODE="0666"' > /etc/udev/rules.d/70-delcom.rules
echo 'Restarting Udev'
service udev restart
echo 'Done'

